### ISSUE TITLE
[Feature]  Add description and tags for this repository

### ISSUE THREAD

**Issue by sushidave** [minutogit/eMinuto-Desktop-Prototype#6]
### Tasks
Add some info for this repo
- [ ] Description: Free and open source software for a self-created, decentral, trust-based digital means of payment.
- [ ] URL: https://eminuto.org
- [ ] Tags: python, kvlang, shell, payment, vouchers, blockchain, vouchers, time vouchers, decentral, eminuto, minuto

**Comment by minutogit** [comment]
almost done. description max 50 signs. Ideas?

**Comment by sushidave** [comment]
How about this description:
`Free wallet for the digital version of 'Minuto'.`
(48 characters) ?
